# Generated by Django 5.1.3 on 2024-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afpuc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="password",
            field=models.CharField(default="senhapadrao", max_length=128),
        ),
    ]
