# Generated by Django 5.1.3 on 2024-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afpuc", "0002_conta_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("F", "Funcionário"),
                    ("C", "Cliente"),
                    ("A", "Cliente Associado"),
                ],
                default="0",
                max_length=1,
            ),
        ),
    ]
