# Generated by Django 5.1.3 on 2024-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afpuc", "0003_conta_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lanche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="lanches/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itens", models.JSONField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
