# Generated by Django 5.1.3 on 2024-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afpuc", "0004_lanche_pedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conta",
            name="matricula",
        ),
        migrations.AddField(
            model_name="conta",
            name="username",
            field=models.CharField(default="teste", max_length=100),
            preserve_default=False,
        ),
    ]
